### ISSUE TITLE
(type *"k8s.io/client-go/rest".Config) as type *"github.com/openshift/client-go/vendor/k8s.io/client-go/rest"

### ISSUE THREAD

**Issue by xiaoxi1989** [openshift/client-go#65]
code : 
```
import (
	"fmt"
	"log"

	buildv1 "github.com/openshift/client-go/build/clientset/versioned/typed/build/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/rest"
)

func main() {

	c := &rest.Config{}
	c.Host = "https://xxxx"
	c.CAData = []byte("xxxx")
	c.CertData = []byte("xxxx")
	c.KeyData = []byte("xxxx")

	buildV1Client, err := buildv1.NewForConfig(c)
	if err != nil {
		log.Fatal(err.Error())
	}
```
go run main.go

`./main.go:25:44: cannot use c (type *"k8s.io/client-go/rest".Config) as type *"github.com/openshift/client-go/vendor/k8s.io/client-go/rest".Config in argument to "github.com/openshift/client-go/build/clientset/versioned/typed/build/v1".NewForConfig`

How to solve this?

**Comment by xiaoxi1989** [comment]
my solution：
glide.yaml
```
- package: github.com/openshift/client-go
  version: ^3.9.0
  subpackages:
  - build/clientset/versioned/typed/build/v1
- package: k8s.io/apimachinery
  version: kubernetes-1.11.2
  subpackages:
  - pkg/apis/meta/v1
- package: k8s.io/api
  version: kubernetes-1.11.2
- package: k8s.io/client-go
  version: 8.0.0
  subpackages:
  - rest
```

then delete 
`vendor/github.com/client-go/vendor/k8s.io`

it works.

but run result is:
`**failed to find any PEM data in certificate input**`
